spring:
  datasource:
    url: jdbc:mysql://root:KGOzQBTPTwZOovQCIdTLvaoTYzWLaZrh@autorack.proxy.rlwy.net:10015/railway?useSSL=false&serverTimeZone=UTC&useLegacyDatetimeCode=false
    username: root
    password: KGOzQBTPTwZOovQCIdTLvaoTYzWLaZrh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
